defaults: &golang
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/hashicorp/packer
  steps:
    - checkout
    - run: go build -ldflags="-s -w" -o ./pkg/packer_$(go env GOOS)_$(go env GOARCH) .
    - run: zip ./pkg/packer_$(go env GOOS)_$(go env GOARCH).zip ./pkg/packer_$(go env GOOS)_$(go env GOARCH)
    - run: rm ./pkg/packer_$(go env GOOS)_$(go env GOARCH)
    - persist_to_workspace:
        root: .
        paths:
          - ./pkg/
version: 2.1
executors:
  golang:
    docker:
      - image: circleci/golang:1.12
commands:
  build-test-binaries:
    parameters:
      GOOS:
        type: string
    steps:
      - checkout
      - run: |
          set -e
          for pkg in $(go list ./...); do
            BIN=testbins/$pkg.test;
            echo $BIN >> testbins/pkglist
            GOOS=<< parameters.GOOS >> go test -vet=off -o $BIN -c $pkg
          done
      - persist_to_workspace:
          root: .
          paths:
            - ./testbins/
  run-test-binaries:
    steps:
      - attach_workspace:
          at: .
      - run: |
          set -e
          for pkg in $(cat pkglist); do 
            echo ${pkg##tests/}
            ./$pkg -test.v
          done

  build-and-persist-packer-binary:
    parameters:
      GOOS:
        type: string
    steps:
      - checkout
      - run: GOOS=<< parameters.GOOS >> go build -ldflags="-s -w" -o ./pkg/packer_<< parameters.GOOS >>_$(go env GOARCH) .
      - run: zip ./pkg/packer_<< parameters.GOOS >>_$(go env GOARCH).zip ./pkg/packer_<< parameters.GOOS >>_$(go env GOARCH)
      - run: rm ./pkg/packer_<< parameters.GOOS >>_$(go env GOARCH)
      - persist_to_workspace:
          root: .
          paths:
            - ./pkg/
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
jobs:
  build-test-binaries-linux:
    executor: golang
    steps:
      - build-test-binaries:
          GOOS: linux
  run-test-binaries-linux:
    executor: golang
    steps:
      - run-test-binaries
  build-test-binaries-darwin:
    executor: golang
    steps:
      - build-test-binaries:
          GOOS: darwin
  build-test-binaries-windows:
    executor: golang
    steps:
      - build-test-binaries:
          GOOS: windows
  check-vendor-vs-mod:
    <<: *golang
    steps:
      - checkout
      - run: GO111MODULE=on go run . --help
      - run: make check-vendor-vs-mod
  check-fmt:
    <<: *golang
    steps:
      - checkout
      - run: make fmt-check
  check-generate:
    <<: *golang
    steps:
      - checkout
      - run: make generate-check
  build_linux:
    executor: golang
    steps:
      - build-and-persist-packer-binary:
          GOOS: linux
  build_windows:
    executor: golang
    steps:
      - build-and-persist-packer-binary:
          GOOS: windows
  build_darwin:
    executor: golang
    steps:
      - build-and-persist-packer-binary:
          GOOS: darwin
  build_freebsd:
    executor: golang
    steps:
      - build-and-persist-packer-binary:
          GOOS: freebsd
  build_solaris:
    executor: golang
    steps:
      - build-and-persist-packer-binary:
          GOOS: solaris
  build_openbsd:
    executor: golang
    steps:
      - build-and-persist-packer-binary:
          GOOS: openbsd
  store_artifacts:
    <<: *golang
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: ./pkg/
          destination: /
  publish-github-tag-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: /go/src/github.com/hashicorp/packer
    steps:
      - attach_workspace:
          at: .
      - run: |
          ghr -prerelease -t ${GITHUB_TOKEN_AZR} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./pkg/
workflows:
  version: 2
  build_and_check_vendor_vs_module:
    jobs:
      - build-test-binaries-linux
      - run-test-binaries-linux:
          requires: 
            - build-test-binaries-linux
      - build-test-binaries-darwin
      - build-test-binaries-windows
      - check-vendor-vs-mod
      - check-fmt
      - check-generate
      - build_linux:
          filters:
            tags:
              only: /.*/
      - build_darwin:
          filters:
            tags:
              only: /.*/
      - build_windows:
          filters:
            tags:
              only: /.*/
      - build_freebsd:
          filters:
            tags:
              only: /.*/
      - build_openbsd:
          filters:
            tags:
              only: /.*/
      - build_solaris:
          filters:
            tags:
              only: /.*/
      - store_artifacts:
          requires:
            - build_linux
            - build_darwin
            - build_windows
            - build_freebsd
            - build_openbsd
            - build_solaris
      - publish-github-tag-release:
          requires:
            - build_linux
            - build_darwin
            - build_windows
            - build_freebsd
            - build_openbsd
            - build_solaris
          filters:
            branches:
              ignore: /.*/
            tags:
              only: nightly
